# SPDX-FileCopyrightText: 2021-2026 The Calyx Institute
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "GCam Photos Preview"
SPDX-PackageSupplier = "The Calyx Institute"
SPDX-PackageDownloadLocation = "https://gitlab.com/CalyxOS/platform_external_calyx_GCamPhotosPreview"

[[annotations]]
path = [".gitignore", "app/.gitignore", ".gitreview", "README.md", "app/src/main/ic_launcher-playstore.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 The Calyx Institute"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradle/wrapper/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007-2023 Gradle, Inc."
SPDX-License-Identifier = "Apache-2.0"
